from pathlib import Path
from typing import Any


def chek_keyring() -> bool: ...


def chek_almacen(data_path: Path) -> bool: ...


def chek_pepper() -> bool: ...


def chek_integridad_json(data_path: Path) -> bool: ...


def chek_firma(data_path: Path) -> bool: ...


def obtener_pin(prompt_head: str) -> bytearray: ...


def validar_pin(data_path: Path, pin: bytearray) -> bool: ...


def guarda_json(data_path: Path, datos: dict[Any, Any]) -> bool: ...


def _cargar_y_verificar_almacen(data_path: Path) -> dict: ...
