from enum import Enum

from PySide6.QtCore import Qt


class EstadoSistema(Enum):
    SIN_KEYRING = ...
    PRIMER_ARRANQUE = ...
    SIN_PEPPER = ...
    FICHERO_CORRUPTO = ...
    FIRMA_INVALIDA = ...
    OK = ...
    SALIENDO_OK = ...
    SALIENDO_ERROR = ...

    def __str__(self) -> str: ...


CURSORES: dict[Enum, Qt.CursorShape]


class Zona(Enum):
    ESQUINA_SUPERIOR_IZQUIERDA = ...
    ESQUINA_SUPERIOR_DERECHA = ...
    ESQUINA_INFERIOR_IZQUIERDA = ...
    ESQUINA_INFERIOR_DERECHA = ...
    BORDE_SUPERIOR = ...
    BORDE_INFERIOR = ...
    BORDE_IZQUIERDO = ...
    BORDE_DERECHO = ...
    BARRA = ...
    INTERIOR = ...


class ErrorApp(Exception): ...
