from dataclasses import dataclass
from enum import Enum

from PySide6.QtCore import Qt


class EstadoApp(Enum):
    SISTEMA_INCOMPATIBLE = ...
    SIN_KEYRING = ...
    PRIMER_ARRANQUE = ...
    SIN_PEPPER = ...
    FICHERO_CORRUPTO = ...
    FIRMA_INVALIDA = ...
    INICIALIZACION_CORRECTA = ...
    SALIENDO_OK = ...
    SALIENDO_ERROR = ...
    AUTORIZADO = ...

    def __str__(self) -> str: ...


@dataclass
class BaseTabla:
    codigo: str

    def __post_init__(self) -> None: ...

    @classmethod
    def reset(cls) -> None: ...


class Zona(Enum):
    ESQUINA_SUPERIOR_IZQUIERDA = ...
    ESQUINA_SUPERIOR_DERECHA = ...
    ESQUINA_INFERIOR_IZQUIERDA = ...
    ESQUINA_INFERIOR_DERECHA = ...
    BORDE_SUPERIOR = ...
    BORDE_INFERIOR = ...
    BORDE_IZQUIERDO = ...
    BORDE_DERECHO = ...
    BARRA = ...
    INTERIOR = ...


CURSORES: dict[Enum, Qt.CursorShape]

TIEMPO_DE_BLOQUEO: dict[int, int]
