from enum import Enum

from PySide6.QtCore import Qt


class EstadoApp(Enum):
    SIN_KEYRING = ...
    PRIMER_ARRANQUE = ...
    SIN_PEPPER = ...
    FICHERO_CORRUPTO = ...
    FIRMA_INVALIDA = ...
    INICIALIZACION_CORRECTA = ...
    SALIENDO_OK = ...
    SALIENDO_ERROR = ...
    AUTORIZADO = ...

    def __str__(self) -> str: ...


class Zona(Enum):
    ESQUINA_SUPERIOR_IZQUIERDA = ...
    ESQUINA_SUPERIOR_DERECHA = ...
    ESQUINA_INFERIOR_IZQUIERDA = ...
    ESQUINA_INFERIOR_DERECHA = ...
    BORDE_SUPERIOR = ...
    BORDE_INFERIOR = ...
    BORDE_IZQUIERDO = ...
    BORDE_DERECHO = ...
    BARRA = ...
    INTERIOR = ...


class ErrorApp(Exception): ...


class PepperNotFoundError(ErrorApp): ...


class FirmaInvalidaError(ErrorApp): ...


class CapturaError(ErrorApp):
    area: tuple | None
    error: Exception | None

    def __init__(self, mensaje: str, area: tuple | None, causa: Exception | None) -> None: ...


CURSORES: dict[Enum, Qt.CursorShape]

TIEMPO_DE_BLOQUEO: dict[int, int]
